# Generated by Django 6.0.4 on 2026-04-22 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurs_verwaltung', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentenausweis',
            name='ausweis_nummer',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentenausweis',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kurs_verwaltung.student'),
        ),
    ]
