# Generated by Django 6.0.4 on 2026-04-22 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurs_verwaltung', '0002_studentenausweis_ausweis_nummer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kurs',
            name='professor',
        ),
        migrations.AddField(
            model_name='kurs',
            name='semester',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='kurs_verwaltung.semester'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professor',
            name='kurs',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='kurs_verwaltung.kurs'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='Kurs',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='kurs_verwaltung.kurs'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kursbeschreibung',
            name='kurs',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kurs_verwaltung.kurs'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester_name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='matrikel_nummer',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='studentenausweis',
            name='ausweis_nummer',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
