# Generated by Django 6.0.4 on 2026-04-22 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurs_verwaltung', '0003_remove_kurs_professor_kurs_semester_professor_kurs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='kurs',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Kurs',
        ),
        migrations.AddField(
            model_name='kurs',
            name='professor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='kurs_verwaltung.professor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kursbeschreibung',
            name='kurs_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='kurs',
            field=models.ManyToManyField(to='kurs_verwaltung.kurs'),
        ),
    ]
