# Generated by Django 6.0.4 on 2026-04-23 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurs_verwaltung', '0004_remove_professor_kurs_remove_student_kurs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kurs',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='kurse_professor', to='kurs_verwaltung.professor'),
        ),
        migrations.AlterField(
            model_name='kurs',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kurse_semester', to='kurs_verwaltung.semester'),
        ),
        migrations.AlterField(
            model_name='student',
            name='kurs',
            field=models.ManyToManyField(related_name='studenten', to='kurs_verwaltung.kurs'),
        ),
    ]
