# Generated by Django 6.0.4 on 2026-04-23 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurs_verwaltung', '0005_alter_kurs_professor_alter_kurs_semester_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kurs',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='professor_kurse', related_query_name='professor_kurs', to='kurs_verwaltung.professor'),
        ),
        migrations.AlterField(
            model_name='kurs',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_kurse', related_query_name='semester_kurs', to='kurs_verwaltung.semester'),
        ),
    ]
