# Generated by Django 6.0.4 on 2026-04-23 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurs_verwaltung', '0006_alter_kurs_professor_alter_kurs_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentenausweis',
            name='student',
        ),
        migrations.AddField(
            model_name='studentenausweis',
            name='student_matrikel_nummer',
            field=models.ForeignKey(default=123456, on_delete=django.db.models.deletion.CASCADE, to='kurs_verwaltung.student', to_field='matrikel_nummer', unique=True),
            preserve_default=False,
        ),
    ]
