# Generated by Django 6.0.4 on 2026-04-24 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurs_verwaltung', '0007_remove_studentenausweis_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentenausweis',
            name='student_matrikel_nummer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentenausweise', related_query_name='studentenausweis', to='kurs_verwaltung.student', to_field='matrikel_nummer', unique=True),
        ),
    ]
