# Generated by Django 6.0.4 on 2026-04-24 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurs_verwaltung', '0008_alter_studentenausweis_student_matrikel_nummer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentenausweis',
            name='student_matrikel_nummer',
        ),
        migrations.AddField(
            model_name='studentenausweis',
            name='student',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='kurs_verwaltung.student'),
            preserve_default=False,
        ),
    ]
